/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import clases.Alumno;
import clases.Materia;
import java.util.HashSet;
import javax.swing.JOptionPane;


/**
 *
 * @author TuMachGalan
 */
public class Escuela extends javax.swing.JFrame {
    private HashSet<Alumno> listaAlumnos= new HashSet<>();
    private HashSet<Materia> listaMaterias= new HashSet<>();
    /**
     * Creates new form Escuela
     */
    public Escuela() {
        initComponents();

    }
    public HashSet<Alumno> getListaAlumnos(){
        return listaAlumnos;
    }
    public HashSet<Materia> getListaMaterias() {
    return listaMaterias;
    }
    
    public void agregarMateria(Materia materia){
        if (listaMaterias.add(materia)){
            JOptionPane.showMessageDialog(null, "Materia Agregada: "+materia,
                "INFORMATION_MESSAGE", JOptionPane.INFORMATION_MESSAGE);
 
        }else{
            JOptionPane.showMessageDialog(null, "La Materia ya existe",
            "ERROR_MESSAGE", JOptionPane.ERROR_MESSAGE);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuAlumno = new javax.swing.JMenu();
        jMenuAlumnoAdd = new javax.swing.JMenuItem();
        jMenuMateria = new javax.swing.JMenu();
        jMenuMateriaAdd = new javax.swing.JMenuItem();
        jMenuRegistro = new javax.swing.JMenu();
        jMenuInscripcionAdd = new javax.swing.JMenuItem();
        jMenuSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Gestion Alumnos");

        escritorio.setBackground(new java.awt.Color(30, 35, 40));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 739, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 522, Short.MAX_VALUE)
        );

        jMenuAlumno.setText("Alumno");

        jMenuAlumnoAdd.setText("Agregar Alumno");
        jMenuAlumnoAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAlumnoAddActionPerformed(evt);
            }
        });
        jMenuAlumno.add(jMenuAlumnoAdd);

        jMenuBar1.add(jMenuAlumno);

        jMenuMateria.setText("Materia");

        jMenuMateriaAdd.setText("Agregar Materia");
        jMenuMateriaAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuMateriaAddActionPerformed(evt);
            }
        });
        jMenuMateria.add(jMenuMateriaAdd);

        jMenuBar1.add(jMenuMateria);

        jMenuRegistro.setText("Registro");
        jMenuRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRegistroActionPerformed(evt);
            }
        });

        jMenuInscripcionAdd.setText("Inscripción");
        jMenuInscripcionAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuInscripcionAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuInscripcionAddActionPerformed(evt);
            }
        });
        jMenuRegistro.add(jMenuInscripcionAdd);

        jMenuBar1.add(jMenuRegistro);

        jMenuSalir.setText("Salir");
        jMenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalirActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuAlumnoAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAlumnoAddActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        AgregarAlumnosView vi = new AgregarAlumnosView(this);
        vi.setVisible(true);
        escritorio.add(vi);
        escritorio.moveToFront(vi);
    }//GEN-LAST:event_jMenuAlumnoAddActionPerformed

    private void jMenuRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuRegistroActionPerformed

    private void jMenuMateriaAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuMateriaAddActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        AgregarMateriaView vi = new AgregarMateriaView(this);
        vi.setVisible(true);
        escritorio.add(vi);
        escritorio.moveToFront(vi);
    }//GEN-LAST:event_jMenuMateriaAddActionPerformed

    private void jMenuInscripcionAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuInscripcionAddActionPerformed
        // TODO add your handling code here: Inscripcion
        escritorio.removeAll();
        escritorio.repaint(); 
        InscripcionAlumnoView vi = new InscripcionAlumnoView(listaAlumnos,listaMaterias);
        vi.setVisible(true);
        escritorio.add(vi);
        escritorio.moveToFront(vi);
    }//GEN-LAST:event_jMenuInscripcionAddActionPerformed

    private void jMenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalirActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
    }//GEN-LAST:event_jMenuSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Escuela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Escuela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Escuela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Escuela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Escuela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenuAlumno;
    private javax.swing.JMenuItem jMenuAlumnoAdd;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuInscripcionAdd;
    private javax.swing.JMenu jMenuMateria;
    private javax.swing.JMenuItem jMenuMateriaAdd;
    private javax.swing.JMenu jMenuRegistro;
    private javax.swing.JMenu jMenuSalir;
    // End of variables declaration//GEN-END:variables
}
